// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Fs.Units")>]
[<assembly: AssemblyProductAttribute("Fs.Units")>]
[<assembly: AssemblyDescriptionAttribute("A simple library for working with units of measure in .NET")>]
[<assembly: AssemblyVersionAttribute("2.0.0")>]
[<assembly: AssemblyFileVersionAttribute("2.0.0")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Fs.Units"
    let [<Literal>] AssemblyProduct = "Fs.Units"
    let [<Literal>] AssemblyDescription = "A simple library for working with units of measure in .NET"
    let [<Literal>] AssemblyVersion = "2.0.0"
    let [<Literal>] AssemblyFileVersion = "2.0.0"
    let [<Literal>] AssemblyConfiguration = "Release"
